### ISSUE TITLE
[Ejercicio Profesional] Aportar contenido sobre las herramientas para la búsqueda laboral

### ISSUE THREAD

**Issue by Daninja111** [dpjagustin/grupo3-aula5-TSDWAD#5]
Dejar plataformas o links de alto valor a la hora de buscar empleo, tanto para la búsqueda laboral como para la elaboración del contenido de presentación personal.

**Comment by Maferdu** [comment]
Hola acabo de realizar la actividad. Herramientas del ejercicio profesional.
